version: "3.8"

services:
  website1:
    image: nginx:alpine
    container_name: website1
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
